x-podman:
  in_pod: false

services:
  cells-sync:
    # image: mcr.microsoft.com/devcontainers/go:1-1.23-bookworm
    build:
      dockerfile: Dockerfile
    container_name: pydio-cells-sync-dev
    userns_mode: keep-id
    volumes:
      # - ../:/workspaces/dummy-mount-to-set-selinux-label:z # Use only for Goland. Required to set the correct selinux label on source dir. Only required for Goland
      - ../:/workspaces/cells-sync:z # Use only for vscode.

    command: /bin/sh -c "while sleep 1000; do :; done"

